version: '3.6'
services:
  ia-telegraf:
    environment:
      no_proxy: "ia-influxdb,ia-opcua-server"
      NO_PROXY: "ia-influxdb,ia-opcua-server"
      OPCUA_SERVER: opc.tcp://ia-opcua-server:4840/freeopcua/server/
    networks:
    - timeseries_network
    volumes:
    - "../sample_apps/windturbine_anomaly_detection/telegraf/config/:/etc/telegraf"
  
  ia-kapacitor:
    volumes:
    - ../sample_apps/windturbine_anomaly_detection/kapacitor/config/:/app/config/
    - ../sample_apps/windturbine_anomaly_detection/kapacitor/udfs/:/app/udfs/
    - ../sample_apps/windturbine_anomaly_detection/kapacitor/tick_scripts/:/app/tick_scripts/
    - ../sample_apps/windturbine_anomaly_detection/kapacitor/config.json:/app/config.json
    - ../sample_apps/windturbine_anomaly_detection/kapacitor/models/:/app/models/

  ia-grafana:
    volumes:
    - ../sample_apps/windturbine_anomaly_detection/grafana/dashboards/windturbine_dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
  ia-opcua-server:
    build:
      context: $PWD/../tools/opcua_server/
      dockerfile: $PWD/../tools/opcua_server/Dockerfile
      args:
        TIMESERIES_USER_NAME: ${TIMESERIES_USER_NAME}
        TIMESERIES_UID: ${TIMESERIES_UID}
    container_name: ia-opcua-server
    hostname: ia-opcua-server
    read_only: true
    image: ${DOCKER_REGISTRY}ia_opcua_server:1.0.0
    restart: unless-stopped
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    ports:
    - "4840:4840"
    networks:
    - timeseries_network
networks:
  timeseries_network:
    driver: bridge
  