# Copyright Intel Corporation

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.mqttbroker.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: mqtt-broker
  ports:
    - name: broker-port
      port: {{ .Values.config.mqttbroker.int.port }}
      targetPort: {{ .Values.config.mqttbroker.int.port }}
      nodePort: {{ .Values.config.mqttbroker.ext.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mqtt-broker
  name: deployment-mqtt-broker
  namespace: {{ .Values.namespace }}

spec:
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
      - name: ia-mqtt-broker
        image: eclipse-mosquitto:2.0.19
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          runAsUser: {{ $.Values.env.TIMESERIES_UID }}
          runAsGroup: {{ $.Values.env.TIMESERIES_UID }}
          readOnlyRootFilesystem: true
        env:
        - name: AppName
          value: "mqtt-broker"
        
        volumeMounts:
        {{ if eq .Values.env.SECURE_MODE true}}
        - name: mosquitto-conf
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: certs
          mountPath: /mosquitto/config/certs
        {{- else }}
        - name: mosquitto-dev-conf
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        {{ end }}

      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-conf
        - name: mosquitto-dev-conf
          configMap:
            name: mosquitto-dev-conf
      {{ if eq .Values.env.SECURE_MODE true}}
        - name: certs
          secret:
            secretName: ts-certs
            items:
            - key: ca_certificate.pem
              path: ca_certificate.pem
            - key: mqtt-broker_Server_server_certificate.pem
              path: mqtt-broker_Server_server_certificate.pem
            - key: mqtt-broker_Server_server_key.pem
              path: mqtt-broker_Server_server_key.pem
      {{ end }}