# Copyright Intel Corporation

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.mqttbroker.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: mqtt-broker
  ports:
    - name: broker-port
      port: {{ .Values.config.mqttbroker.int.port }}
      targetPort: {{ .Values.config.mqttbroker.int.port }}
      nodePort: {{ .Values.config.mqttbroker.ext.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mqtt-broker
  name: deployment-mqtt-broker
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
      - name: ia-mqtt-broker
        image: eclipse-mosquitto:2.0.19
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          runAsUser: {{ $.Values.env.TIMESERIES_UID }}
          runAsGroup: {{ $.Values.env.TIMESERIES_UID }}
          readOnlyRootFilesystem: true
        env:
        - name: AppName
          value: "mqtt-broker"
        volumeMounts:
        - name: mosquitto-conf
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-conf