#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
{{ if eq .Values.env.SECURE_MODE true}}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: cert-generator
  name: job-cert-generator
  namespace: {{ .Values.namespace }}

spec:
  template:
    metadata:
      labels:
        app: cert-generator
    spec:
      serviceAccountName: pod-read-sa
      
      {{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      containers:
      - name: ia-cert-generator
        image: {{ .Values.DOCKER_REGISTRY }}ia-cert-generator:1.0.0
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          readOnlyRootFilesystem: true
            
        volumeMounts:
        - name: tmpfs-volume
          mountPath: /app/Certificates
      restartPolicy: Never
      volumes:
        - name: tmpfs-volume
          emptyDir: {}
{{ end }}