#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.config.gradio_ui.name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: NodePort
  selector:
    app: gradio-ui
  ports:
  - name: gradio-ui-port
    port: {{ $.Values.config.gradio_ui.int.port }}
    targetPort: {{ $.Values.config.gradio_ui.int.port }}
    nodePort: {{ $.Values.config.gradio_ui.ext.port }}
  
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: gradio-ui
  name: deployment-gradio-ui
  namespace: {{ $.Values.namespace }}

spec:
  selector:
    matchLabels:
      app: gradio-ui
  template:
    metadata:
      labels:
        app: gradio-ui
    spec:
      {{- if and $.Values.DOCKER_USERNAME $.Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      containers:
      - name: ia-gradio-ui
        image:  {{ .Values.DOCKER_REGISTRY }}ia-gradio-ui:1.0.0
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: vol-temp-gradio
          mountPath: /tmp
        {{ if eq .Values.env.SECURE_MODE true}}
        - name: certs
          mountPath: /run/secrets/ca_certificate.pem
          subPath: ca_certificate.pem
        - name: certs
          mountPath: /run/secrets/gradio-ui_Server_server_certificate.pem
          subPath: gradio-ui_Server_server_certificate.pem
        - name: certs
          mountPath: /run/secrets/gradio-ui_Server_server_key.pem
          subPath: gradio-ui_Server_server_key.pem
        {{ end }}
        env:
        - name: SECURE_MODE
          value: '{{ $.Values.env.SECURE_MODE }}'
        - name: INFLUXDB_USERNAME
          value: '{{ $.Values.env.INFLUXDB_USERNAME }}'
        - name: INFLUXDB_PASSWORD
          value: '{{ $.Values.env.INFLUXDB_PASSWORD }}'
        - name: INFLUX_SERVER
          value: "influxdb"
        - name: INFLUXDB_DB
          value: "datain"
        - name: LOG_LEVEL
          value: '{{ $.Values.env.LOG_LEVEL }}'
      volumes:
      - name: vol-temp-gradio
        emptyDir: {}
      {{ if eq .Values.env.SECURE_MODE true}}
      - name: certs
        secret:
          secretName: ts-certs
          items:
          - key: ca_certificate.pem
            path: ca_certificate.pem 
          - key: gradio-ui_Server_server_certificate.pem
            path: gradio-ui_Server_server_certificate.pem
          - key: gradio-ui_Server_server_key.pem
            path: gradio-ui_Server_server_key.pem
      {{ end }}
          
