# Copyright Intel Corporation

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.kapacitor.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.config.kapacitor.kapacitor_port }}
    name: kapacitor-port
  selector:
    app: kapacitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kapacitor
  name: deployment-kapacitor
  namespace: {{ .Values.namespace }}

spec:
  selector:
    matchLabels:
      app: kapacitor
  template:
    metadata:
      labels:
        app: kapacitor
    spec:
      {{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      containers:
      - name: ia-kapacitor
        image: {{ .Values.DOCKER_REGISTRY }}ia-kapacitor:1.0.0
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: vol-temp-kapacitor
          mountPath: /tmp
        - name: {{ .Values.volumes.models.name }}
          mountPath: {{ .Values.volumes.models.location }}
        - name: {{ .Values.volumes.tick.name }}
          mountPath: {{ .Values.volumes.tick.location }}
        - name: {{ .Values.volumes.udfs.name }}
          mountPath: {{ .Values.volumes.udfs.location }}
        - name: kapacitor-config
          mountPath: /app/config.json
          subPath: config.json
        {{ if eq .Values.env.SECURE_MODE true}}
        - name: certs
          mountPath: /run/secrets/Kapacitor_Server
        {{ end }}

        env:
        - name: HTTP_PROXY
          value: '{{ .Values.env.HTTP_PROXY }}'
        - name: HTTPS_PROXY
          value: '{{ .Values.env.HTTPS_PROXY }}'
        - name: NO_PROXY
          value: "influxdb,kapacitor,ia-mqtt-broker"
        - name: TIMESERIES_NO_PROXY
          value: '{{ .Values.env.TIMESERIES_NO_PROXY }}'
        - name: SECURE_MODE
          value: '{{ .Values.env.SECURE_MODE }}'
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: python
        - name: KAPACITOR_INFLUXDB_0_USERNAME
          value: '{{ .Values.env.INFLUXDB_ADMIN_USERNAME }}'
        - name: KAPACITOR_PORT
          value: '{{ .Values.config.kapacitor.kapacitor_port }}'
        - name: KAPACITOR_INFLUXDB_0_PASSWORD
          value: '{{ .Values.env.INFLUXDB_ADMIN_PASSWORD }}'
        - name: KAPACITOR_URL
          value: "http://kapacitor:{{ .Values.config.kapacitor.kapacitor_port }}/"
        - name: KAPACITOR_UNSAFE_SSL
          value: "true"
        - name: KAPACITOR_INFLUXDB_0_URLS_0
          value: "http://influxdb:{{ .Values.config.influx_db_server.influx_http }}/"
        - name: INFLUX_SERVER
          value: "influxdb"
        - name: KAPACITOR_SERVER
          value: "kapacitor"
        - name: INFLUXDB_PORT
          value: "8086"
        - name: PROFILING_MODE
          value: "false"
        - name: KAPACITOR_LOGGING_LEVEL
          value: '{{ .Values.env.LOG_LEVEL }}'
        - name: MQTT_BROKER_HOST
          value: "ia-mqtt-broker" 
        - name: MQTT_BROKER_PORT
          value: "1883" 
      volumes:
      - name: vol-temp-kapacitor
        emptyDir: {}
      - name: kapacitor-config
        configMap:
          name: kapacitor-config
      - name: {{ .Values.volumes.models.name }}
        hostPath:
          path: {{ .Values.volumes.models.hostpath }}
      - name: {{ .Values.volumes.tick.name }}
        hostPath:
          path: {{ .Values.volumes.tick.hostpath }}
      - name: {{ .Values.volumes.udfs.name }}
        hostPath:
          path: {{ .Values.volumes.udfs.hostpath }}

      {{ if eq .Values.env.SECURE_MODE true}}
      - name: certs
        secret:
          secretName: ts-certs
          items:
          - key: ca_certificate.pem
            path: ca_certificate.pem 
          - key: Kapacitor_Server_server_certificate.pem
            path: Kapacitor_Server_server_certificate.pem
          - key: Kapacitor_Server_server_key.pem
            path: Kapacitor_Server_server_key.pem
      {{ end }}