# Copyright Intel Corporation

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegraf
  name: deployment-telegraf
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      {{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      containers:
      - name: ia-telegraf
        image: telegraf:1.33.1
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmpfs-volume
          mountPath: /tmp
        - name: telegraf-dev-config
          mountPath: /etc/telegraf/Telegraf_devmode.conf
          subPath: Telegraf_devmode.conf
        - name: telegraf-config
          mountPath: /etc/telegraf/Telegraf.conf
          subPath: Telegraf.conf
        env:
        - name: SECURE_MODE
          value: '{{ .Values.env.SECURE_MODE }}'
        - name: MQTT_BROKER_HOST
          value: {{ .Values.config.telegraf.MQTT_BROKER_HOST }}
        - name: INFLUXDB_USERNAME
          value: '{{ .Values.env.INFLUXDB_USERNAME }}'
        - name: INFLUXDB_PASSWORD
          value: '{{ .Values.env.INFLUXDB_PASSWORD }}'
        - name: INFLUX_SERVER
          value: "influxdb"
        - name: INFLUXDB_DBNAME
          value: "datain"
        - name: INFLUXDB_PORT
          value: "8086"
        - name: TELEGRAF_CONFIG_PATH
          value: /etc/telegraf/Telegraf_devmode.conf
        - name: OPCUA_SERVER
          value: "opc.tcp://opcua-server:4840/freeopcua/server/"
      volumes:
      - name: tmpfs-volume
        emptyDir: {}
      - name: telegraf-dev-config
        configMap:
          name: telegraf-dev-conf-input
      - name: telegraf-config
        configMap:
          name: telegraf-conf-input
