{
 "title": "Wind Turbine Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Anomaly Prediction for Grid Active Power",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT grid_active_power,wind_speed from wind_turbine_anomaly_data",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wind_turbine_anomaly_data",
     "query": "SELECT anomaly_status FROM wind_turbine_anomaly_data where anomaly_status>0",
     "select": [
      [
       { "params": [ "anomaly_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Low Anomaly",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Low Anomaly",
     "query": "SELECT count(anomaly_status)  FROM \"wind_turbine_anomaly_data\" WHERE (\"anomaly_status\" =  0.3) "
    }
   ]
  },
  {
   "title": "Medium Anomaly",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Medium Anomaly",
     "query": "SELECT count(anomaly_status) FROM \"wind_turbine_anomaly_data\" WHERE (\"anomaly_status\" =  0.6) "
    }
   ]
  },
  {
   "title": "High Anomaly",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "High Anomaly",
     "query": "SELECT count(anomaly_status) FROM \"wind_turbine_anomaly_data\" WHERE (\"anomaly_status\" =  1) "
    }
   ]
  },
  {
   "title": "Total Anomaly Detected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wind_turbine_anomaly_data",
     "query": "SELECT count(\"wind_speed\") FROM \"wind_turbine_anomaly_data\" where anomaly_status>0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Ingested Points",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(Feed) AS mean_value FROM weld_data\n"
    }
   ]
  },
  {
   "title": "Total Processed Points",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weld_anomaly_data",
     "query": "SELECT count(\"Feed\") FROM \"weld_anomaly_data\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ingestion Rate (Points Per Minute)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(mean_value) FROM (SELECT count(wind_speed) AS mean_value FROM weld_data  WHERE time > now() - 3m GROUP BY time(1m))\n"
    }
   ]
  },
  {
   "title": "Analytics Processing Rate (Points Per Minute)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(mean_value) FROM (SELECT count(wind_speed) AS mean_value FROM wind_turbine_anomaly_data  WHERE time > now() - 3m GROUP BY time(1m))\n"
    }
   ]
  },
  {
   "title": "Average Time to Process a point E2E (Seconds)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(mean_value) FROM (\n  SELECT mean(end_end_time)/1000000000 AS mean_value FROM wind_turbine_anomaly_data\n  WHERE analytic=1 and time > now() - 3m\n  GROUP BY time(1m)\n)\n"
    }
   ]
  },
  {
   "title": "Analytics Processing Time (Seconds)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": " select mean(processing_time)/1000000000 from wind_turbine_anomaly_data where analytic=1 order by time desc"
    }
   ]
  }
 ]
}