#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

namespace: apps
DOCKER_REGISTRY: ''
DOCKER_USERNAME: ''
DOCKER_PASSWORD: ''
imagePullPolicy: IfNotPresent
storageClassName: manual
env:
  SECURE_MODE: true 
  PROFILING_MODE: false
  TELEGRAF_INPUT_PLUGIN: opcua
  TIMESERIES_USER_NAME: timeseries_user
  TIMESERIES_UID: 1999
  TIMESERIES_NO_PROXY: influxdb,time-series-analytics-microservice,mqttbroker,ia-mqtt-broker,ia-opcua-server
  INFLUXDB_USERNAME: 
  INFLUXDB_PASSWORD: 
  VISUALIZER_GRAFANA_USER: 
  VISUALIZER_GRAFANA_PASSWORD: 
  timeseries_no_proxy: localhost,127.0.0.1,.intel.com
  HTTP_PROXY: 
  HTTPS_PROXY: 
  INFLUXDB_RETENTION_DURATION: 1h0m0s
  TELEGRAF_METRIC_BATCH_SIZE: 100
  LOG_LEVEL: INFO
  ENABLE_MODEL_REGISTRY: false
  AppName: ModelRegistry
  CA_CERT: /run/secrets/modelregistry-server/server-ca.crt
  ENABLE_HTTPS_MODE: false
  MIN_LOG_LEVEL: DEBUG
  MINIO_ACCESS_KEY: intel
  MINIO_BUCKET_NAME: model-registry
  MINIO_HOSTNAME: mraas-minio
  MINIO_SECRET_KEY: 
  MINIO_SERVER_PORT: "8000"
  MLFLOW_S3_ENDPOINT_URL: http://127.0.0.1:8000
  SERVER_CERT: /run/secrets/modelregistry-server/public.crt
  SERVER_PORT: "8111"
  SERVER_PRIVATE_KEY: /run/secrets/modelregistry-server/private.key 
  no_proxy: mraas-minio
  NO_PROXY: mraas-minio
  MR_USER_NAME: mruser
  MR_UID: 2025
  POSTGRES_DB: model_registry_db
  POSTGRES_PASSWORD: 
  POSTGRES_USER: postgres
images:
  model_registry: intel/model-registry:1.0.3
config:
  influx_db_server:
    name: influxdb
    influx_http: 8086
  grafana:
    name: grafana
    int:
      port: "3000"
    ext:
      port: "30001"
  telegraf:
    name: telegraf
    MQTT_BROKER_HOST: "ia-mqtt-broker"
  time_series_analytics_microservice:
    name: time-series-analytics-microservice
    kapacitor_port: 9092
  mqttbroker:
    name: ia-mqtt-broker
    int:
      port: 1883
    ext:
      port: 30006
  opcuaserver:
    name: ia-opcua-server
    int:
      pub_port: 4840
  mqttpublisher:
      name: mqttpublisher
  gradio_ui:
    name: gradio-ui
    int:
      port: "7860"
    ext:
      port: "30002"
  model_registry:
    name: model-registry
    int:
      port: "8111"
    ext:
      port: "32002"
