# Copyright Intel Corporation

namespace: apps
DOCKER_REGISTRY: ''
DOCKER_USERNAME: ''
DOCKER_PASSWORD: ''
imagePullPolicy: IfNotPresent
storageClassName: manual
env:
  SECURE_MODE: true 
  PROFILING_MODE: false
  TELEGRAF_INPUT_PLUGIN: opcua
  TIMESERIES_USER_NAME: timeseries_user
  TIMESERIES_UID: 1999
  TIMESERIES_NO_PROXY: influxdb,kapacitor,mqttbroker,ia-mqtt-broker,opcua-server
  INFLUXDB_ADMIN_USERNAME: 
  INFLUXDB_ADMIN_PASSWORD: 
  INFLUXDB_USERNAME: 
  INFLUXDB_PASSWORD: 
  VISUALIZER_GRAFANA_USER: 
  VISUALIZER_GRAFANA_PASSWORD: 
  timeseries_no_proxy: localhost,127.0.0.1,.intel.com
  HTTP_PROXY: 
  HTTPS_PROXY:
  INFLUXDB_RETENTION_DURATION: 1h0m0s
  DEPLOYMENT_METHOD_ITEP: false
config:
  influx_db_server:
    name: influxdb
    influx_http: 8086
  grafana:
    name: grafana
    int:
      port: "3000"
    ext:
      port: "30001"
  telegraf:
    name: telegraf
    MQTT_BROKER_HOST: "ia-mqtt-broker"
  kapacitor:
    name: kapacitor
    kapacitor_port: 9092
  mqttbroker:
    name: ia-mqtt-broker
    int:
      port: 1883
    ext:
      port: 30006
  opcuaserver:
    name: opcua-server
    int:
      pub_port: 4840
  mqttpublisher:
      name: mqttpublisher
volumes:
  models:
    name: vol-models
    size: 500Mi
    hostpath: "/opt/intel/kapacitor/models/"
    location: "/app/models"
  tick:
    name: vol-tick-scripts
    size: 100Mi
    hostpath: "/opt/intel/kapacitor/tick_scripts/"
    location: "/app/tick_scripts"
  udfs:
    name: vol-udfs
    size: 100Mi
    hostpath: "/opt/intel/kapacitor/udfs/"
    location: "/app/udfs"
